### ISSUE TITLE
About Vulnhub RSA:1(https://hackso.me/rsa-1-walkthrough/)

### ISSUE THREAD

**Issue by dds2333** [limbernie/limbernie.github.io#1]
Hello，i try to import RSAfun2018.ova(virtualbox 5.2.16) but failed. then test the ova and found it was broken (https://www.vulnhub.com/entry/rsa-1,255/). do you have the complete ova? thanks

**Comment by limbernie** [comment]
You can try the VulnHub mirror:
https://download.vulnhub.com/rsa/RSAfun2018.ova

**Comment by dds2333** [comment]
I've tried. But it didn’t work. Thank you anway.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Bernie Lim<mailto:notifications@github.com>
发送时间: 2019年12月3日 11:30
收件人: limbernie/limbernie.github.io<mailto:limbernie.github.io@noreply.github.com>
抄送: 小生<mailto:dds2014@live.cn>; Author<mailto:author@noreply.github.com>
主题: Re: [limbernie/limbernie.github.io] About Vulnhub RSA:1(https://hackso.me/rsa-1-walkthrough/) (#1)


Closed #1<https://github.com/limbernie/limbernie.github.io/issues/1>.

―
